table fact_passage
	lineageTag: 7d0146fe-273b-45b1-9d57-1f71b181efc7

	measure 'Passages mesurables' = CALCULATE(COUNTROWS(fact_passage), NOT ISBLANK(fact_passage[is_punctual]))
		formatString: #,0
		lineageTag: 8abb60b0-954e-4973-9d5e-157ccaac1297

	measure 'Passages ponctuels' = CALCULATE(SUM(fact_passage[is_punctual]), NOT ISBLANK(fact_passage[is_punctual]))
		formatString: #,0
		lineageTag: c22ee540-34f8-4cc1-af07-6892e8bc9fa8

	measure 'Taux de ponctualite' = DIVIDE([Passages ponctuels], [Passages mesurables])
		formatString: 0.0%
		lineageTag: f55a59a6-9444-49bc-83ab-8df30955238a

	measure 'Retard moyen (min)' = DIVIDE(AVERAGE(fact_passage[arrival_delay_s]), 60)
		formatString: 0.0
		lineageTag: 31646d77-c033-49ae-8b5d-a9fe22069dab

	measure 'Trains supprimes' = CALCULATE(COUNTROWS(fact_passage), fact_passage[schedule_relationship] = "CANCELED")
		formatString: #,0
		lineageTag: de8da4fd-6fed-4709-8a54-ada387dd96ec

	/// Taux de ponctualite sur les passages effectivement observes : deja realises (is_past)
	/// et survenus pendant une heure surveillee par le collecteur (is_collected), avec au moins
	/// 20 passages. Les passages vus apres coup sont un echantillon biaise vers les trains longs.
	measure 'Taux ponctualite observe' = VAR Observed = CALCULATE([Passages mesurables], fact_passage[is_collected] = 1, fact_passage[is_past] = 1) RETURN IF(Observed >= 20, CALCULATE([Taux de ponctualite], fact_passage[is_collected] = 1, fact_passage[is_past] = 1))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 4b7d2e19-6c83-4f0a-9e25-b1a8d37c5f42

	column service_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: fdb3f313-a0d6-4e53-84a9-f4370039c80e
		summarizeBy: none
		sourceColumn: service_date

		variation Variation
			isDefault
			relationship: 44705432-0f54-4647-bc19-5b45fff135b4
			defaultHierarchy: LocalDateTable_fdb5a621-2c53-41e0-a516-670a11e01003.'Hiérarchie de dates'

		annotation UnderlyingDateTimeDataType = Date

	column trip_id
		dataType: string
		lineageTag: d304d468-b6a5-48d0-ab91-71f8aaa738f9
		summarizeBy: none
		sourceColumn: trip_id

	column route_id
		dataType: string
		lineageTag: ba4094a2-5b22-497d-bd0c-96c4b6254e20
		summarizeBy: none
		sourceColumn: route_id

	column stop_id
		dataType: string
		lineageTag: 634803c6-3180-4b79-8f79-23a3880949f3
		summarizeBy: none
		sourceColumn: stop_id

	column stop_sequence
		dataType: int64
		lineageTag: fffd8e13-ca54-47f0-90fd-2347b6b4d0e1
		summarizeBy: sum
		sourceColumn: stop_sequence

		annotation SummarizationSetBy = Automatic

	column scheduled_arrival
		dataType: string
		lineageTag: 0e0a8d96-679a-4c63-a299-1aa8ec6c9541
		summarizeBy: none
		sourceColumn: scheduled_arrival

	column scheduled_minutes
		dataType: int64
		lineageTag: 35d03e10-c846-43d6-ad30-f5a7b00ceace
		summarizeBy: sum
		sourceColumn: scheduled_minutes

		annotation SummarizationSetBy = Automatic

	column scheduled_hour
		dataType: int64
		lineageTag: edb0f3f9-d5aa-46c5-8c19-58d3f3573371
		summarizeBy: sum
		sourceColumn: scheduled_hour

		annotation SummarizationSetBy = Automatic

	column arrival_delay_s
		dataType: int64
		lineageTag: 0b6adaac-c786-4cb6-9327-0d8038d008ae
		summarizeBy: sum
		sourceColumn: arrival_delay_s

		annotation SummarizationSetBy = Automatic

	column departure_delay_s
		dataType: int64
		lineageTag: 5793ce42-75e4-4540-97b0-13f9b8afe846
		summarizeBy: sum
		sourceColumn: departure_delay_s

		annotation SummarizationSetBy = Automatic

	column schedule_relationship
		dataType: string
		lineageTag: 8ba4366f-fbcf-453e-aa2c-3aed80efbc70
		summarizeBy: none
		sourceColumn: schedule_relationship

	column is_punctual
		dataType: int64
		lineageTag: a9eb0cb3-2a19-4551-b14e-16b5b025fb7b
		summarizeBy: sum
		sourceColumn: is_punctual

		annotation SummarizationSetBy = Automatic

	column observed_at
		dataType: int64
		lineageTag: 52cc8dea-dcbf-4be3-866b-da5abdb02a99
		summarizeBy: sum
		sourceColumn: observed_at

		annotation SummarizationSetBy = Automatic

	column arrival_time
		dataType: int64
		lineageTag: 1c4f0a92-7d55-4b8e-9a31-6f0e2d8b4417
		summarizeBy: none
		sourceColumn: arrival_time

	column is_past
		dataType: int64
		lineageTag: 8e2b5d61-04a7-4f39-bb52-c9d31a7e6f80
		summarizeBy: none
		sourceColumn: is_past

	column is_collected
		dataType: int64
		lineageTag: d2a64f07-5e19-4b3c-8a70-3f9e1c6b8d25
		summarizeBy: none
		sourceColumn: is_collected

	partition fact_passage = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataFolder & "\fact_passage.csv"), [Delimiter = ",", Columns = 16, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					// "en-US" so the ISO service_date parses under the fr-FR model culture.
					Typed = Table.TransformColumnTypes(Headers, {{"service_date", type date}, {"trip_id", type text}, {"route_id", type text}, {"stop_id", type text}, {"stop_sequence", Int64.Type}, {"scheduled_arrival", type text}, {"scheduled_minutes", Int64.Type}, {"scheduled_hour", Int64.Type}, {"arrival_delay_s", Int64.Type}, {"departure_delay_s", Int64.Type}, {"schedule_relationship", type text}, {"is_punctual", Int64.Type}, {"arrival_time", Int64.Type}, {"is_past", Int64.Type}, {"observed_at", Int64.Type}, {"is_collected", Int64.Type}}, "en-US")
				in
					Typed

